#!/bin/bash

sed -i "s/\bAA\b/aa/g" lexicon_cls
sed -i "s/\bAE\b/axx/g" lexicon_cls
sed -i "s/\bAH\b/a/g" lexicon_cls
sed -i "s/\bAO\b/ax/g" lexicon_cls
sed -i "s/\bAW\b/ou/g" lexicon_cls
sed -i "s/\bAX\b/a/g" lexicon_cls
sed -i "s/\bAY\b/ei/g" lexicon_cls
sed -i "s/\bB\b/b/g" lexicon_cls
sed -i "s/\bCH\b/c/g" lexicon_cls
sed -i "s/\bD\b/dx/g" lexicon_cls
sed -i "s/\bDH\b/d/g" lexicon_cls
sed -i "s/\bEH\b/ee/g" lexicon_cls
sed -i "s/\bER\b/a' 'r/g" lexicon_cls
sed -i "s/\bEY\b/ee/g" lexicon_cls
sed -i "s/\bF\b/f/g" lexicon_cls
sed -i "s/\bG\b/g/g" lexicon_cls
sed -i "s/\bHH\b/h/g" lexicon_cls
sed -i "s/\bIH\b/i/g" lexicon_cls
sed -i "s/\bIY\b/ii/g" lexicon_cls
sed -i "s/\bJH\b/j/g" lexicon_cls
sed -i "s/\bK\b/k/g" lexicon_cls
sed -i "s/\bL\b/l/g" lexicon_cls
sed -i "s/\bM\b/m/g" lexicon_cls
sed -i "s/\bN\b/n/g" lexicon_cls
sed -i "s/\bNG\b/ng/g" lexicon_cls
sed -i "s/\bOW\b/o/g" lexicon_cls
sed -i "s/\bOY\b/ei/g" lexicon_cls
sed -i "s/\bP\b/p/g" lexicon_cls
sed -i "s/\bR\b/r/g" lexicon_cls
sed -i "s/\bS\b/s/g" lexicon_cls
sed -i "s/\bSH\b/sh/g" lexicon_cls
sed -i "s/\bT\b/tx/g" lexicon_cls
sed -i "s/\bTH\b/t/g" lexicon_cls
sed -i "s/\bUH\b/u/g" lexicon_cls
sed -i "s/\bUW\b/uu/g" lexicon_cls
sed -i "s/\bV\b/w/g" lexicon_cls
sed -i "s/\bW\b/w/g" lexicon_cls
sed -i "s/\bY\b/y/g" lexicon_cls
sed -i "s/\bZ\b/z/g" lexicon_cls
sed -i "s/\bZH\b/sh/g" lexicon_cls
